--MINOR CLEANING

ALTER TABLE DRUG_MAPPER
ADD CLEANED_DRUGNAME  VARCHAR(600);
GO

ALTER TABLE DRUG_MAPPER
ADD CLEANED_PROD_AI  VARCHAR(500);
GO


--CLEAN PATTERN ---->>   LASILIX             /00032601/>>> LASIX
UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =
CASE WHEN PATINDEX('%/[0-9][0-9][0-9][0-9][0-9]%/%', [DRUGNAME]) > 0	
THEN LEFT([DRUGNAME], PATINDEX('%/[0-9][0-9][0-9][0-9][0-9]%/%', [DRUGNAME]) - 1)
ELSE [DRUGNAME] END
WHERE NOTES IS NULL

 -- CLEAN PATTERN-->>   LASILIX             /USA/>>> LASIX
UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME  = LEFT(CLEANED_DRUGNAME, CHARINDEX('   /', CLEANED_DRUGNAME) - 1)
	WHERE CHARINDEX('   /', CLEANED_DRUGNAME) > 0
	AND NOTES IS NULL

----------------------------------------------------
-- WHITE SPACES
UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
WHERE NOTES IS NULL
GO
---------------------------------------------------
UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '|' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, ',' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '+' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, ';' , ' / ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, ' -' , ' ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, ' –' , ' ')
WHERE NOTES IS NULL
GO
UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '–' , ' ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '\' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '/' , ' / ')
WHERE NOTES IS NULL

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =  REPLACE (CLEANED_DRUGNAME, '  ' , ' ')
WHERE NOTES IS NULL
GO

----------------------------------
--CLEAN PATTERN ---->>   LASILIX             /00032601/>>> LASIX
UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =
CASE WHEN PATINDEX('%/[0-9][0-9][0-9][0-9][0-9]%/%', PROD_AI) > 0	
THEN LEFT(PROD_AI, PATINDEX('%/[0-9][0-9][0-9][0-9][0-9]%/%', PROD_AI) - 1)
ELSE PROD_AI END
WHERE NOTES IS NULL

----------------------------------------------------
-- WHITE SPACES
UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
WHERE NOTES IS NULL
GO

------------------------------------------------------
UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '|' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, ',' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '+' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, ';' , ' / ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, ' -' , ' ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, ' –' , ' ')
WHERE NOTES IS NULL
GO
UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '–' , ' ')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '\' , '/')
WHERE NOTES IS NULL
GO

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '/' , ' / ')
WHERE NOTES IS NULL

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =  REPLACE (CLEANED_PROD_AI, '  ' , ' ')
WHERE NOTES IS NULL
GO




--MAPPING AFTER CLEANING


------------------------------------------
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.1
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
	-----------------------------------------
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.2
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI)>0 AND CHARINDEX(')',CLEANED_PROD_AI)> CHARINDEX('(', CLEANED_PROD_AI) 
		THEN SUBSTRING(CLEANED_PROD_AI,CHARINDEX('(', CLEANED_PROD_AI)+1,CHARINDEX(')',CLEANED_PROD_AI)-CHARINDEX('(',CLEANED_PROD_AI)-1)
		 ELSE CLEANED_PROD_AI  END
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
	
--------------------------------------------
--MATCH WITH OUTSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.3
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
		
------------------------------------------------------------------------------

--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.5
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
	INNER JOIN RXNCONSO ON IDD.RXAUI = RXNCONSO.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')

--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.6
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_PROD_AI) > 0  AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
 THEN
 SUBSTRING(CLEANED_PROD_AI,CHARINDEX('(', CLEANED_PROD_AI)+1,CHARINDEX(')',CLEANED_PROD_AI)-CHARINDEX('(',CLEANED_PROD_AI)-1) ELSE NULL END
		  )
	INNER JOIN RXNCONSO ON IDD.RXAUI = RXNCONSO.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
		

--MATCH WITH OUTSIDE ()	

UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.7
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
	
--------------------
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.8
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI) > 0 AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
			THEN STUFF(CLEANED_PROD_AI, CHARINDEX('(', CLEANED_PROD_AI), (CHARINDEX(')', CLEANED_PROD_AI) - CHARINDEX('(', CLEANED_PROD_AI)) + 1, '')
		ELSE CLEANED_PROD_AI
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
	
----------------------------------------------------------------------
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.9
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
		 WHERE  NOTES IS NULL
	
		AND [RXNCONSO].TTY = 'IN'

	------------------------------------	
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.10
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI)>0 AND CHARINDEX(')',CLEANED_PROD_AI)> CHARINDEX('(', CLEANED_PROD_AI) 
		THEN SUBSTRING(CLEANED_PROD_AI,CHARINDEX('(', CLEANED_PROD_AI)+1,CHARINDEX(')',CLEANED_PROD_AI)-CHARINDEX('(',CLEANED_PROD_AI)-1)
		  
			 ELSE CLEANED_PROD_AI  END
		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY ='IN'
	--------------------------------------------------------
	--MATCH WITH OUTSIDE ()	
   
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.11
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
		 WHERE  NOTES IS NULL
	
		AND [RXNCONSO].TTY = 'IN'
	
-------------------------------------------------------------

--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.13
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
	INNER JOIN RXNCONSO ON IDD.RXAUI = RXNCONSO.RXAUI
		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY = 'IN'

		
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.14
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_PROD_AI) > 0  AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
 THEN
 SUBSTRING(CLEANED_PROD_AI,CHARINDEX('(', CLEANED_PROD_AI)+1,CHARINDEX(')',CLEANED_PROD_AI)-CHARINDEX('(',CLEANED_PROD_AI)-1) ELSE NULL END
		  )
	INNER JOIN RXNCONSO ON IDD.RXAUI = RXNCONSO.RXAUI
		 WHERE  NOTES IS NULL
	
		AND [RXNCONSO].TTY = 'IN'
		-----------------------------------------------------------------

	UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.15
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 
		AND [RXNCONSO].TTY ='IN'
		
--------------------
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.16
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI) > 0 AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
			THEN STUFF(CLEANED_PROD_AI, CHARINDEX('(', CLEANED_PROD_AI), (CHARINDEX(')', CLEANED_PROD_AI) - CHARINDEX('(', CLEANED_PROD_AI)) + 1, '')
		ELSE CLEANED_PROD_AI
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY = 'IN'
	
------------------------------------------------------------------
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.17
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
		 WHERE  NOTES IS NULL
	
-----------------------------------		
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.18
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI)>0 AND CHARINDEX(')',CLEANED_PROD_AI)> CHARINDEX('(', CLEANED_PROD_AI) 
		THEN SUBSTRING(CLEANED_PROD_AI,CHARINDEX('(', CLEANED_PROD_AI)+1,CHARINDEX(')',CLEANED_PROD_AI)-CHARINDEX('(',CLEANED_PROD_AI)-1)
			 ELSE CLEANED_PROD_AI  END
		 WHERE  NOTES IS NULL

-----------------------------------------------
--MATCH WITH OUTSIDE ()	
  
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.19
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
		 WHERE  NOTES IS NULL
	
----------------------------------------------------------------------------
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.21
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = (
CASE 	WHEN  
 CHARINDEX('(',CLEANED_DRUGNAME) > 0  AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
 THEN
 SUBSTRING(CLEANED_DRUGNAME,CHARINDEX('(', CLEANED_DRUGNAME)+1,CHARINDEX(')',CLEANED_DRUGNAME)-CHARINDEX('(',CLEANED_DRUGNAME)-1) ELSE NULL END
		  )
	INNER JOIN RXNCONSO ON IDD.RXAUI = RXNCONSO.RXAUI
		 WHERE  NOTES IS NULL
	
---------------------------------------------------------------	
	UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.23
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		
----------------------------------------------------------------
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 8.24
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI) > 0 AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
			THEN STUFF(CLEANED_PROD_AI, CHARINDEX('(', CLEANED_PROD_AI), (CHARINDEX(')', CLEANED_PROD_AI) - CHARINDEX('(', CLEANED_PROD_AI)) + 1, '')
		ELSE CLEANED_PROD_AI
	END
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL 
		
-------------------------------------------------------


   --REMOVE BRACKETS
 DECLARE @COUNTER INT 
SET @COUNTER=1
WHILE ( @COUNTER <= 10)
BEGIN
 UPDATE DRUG_MAPPER  
SET CLEANED_DRUGNAME = CASE 
		WHEN CHARINDEX('(', CLEANED_DRUGNAME) > 0 AND CHARINDEX(')', CLEANED_DRUGNAME) > 0 AND CHARINDEX('(', CLEANED_DRUGNAME) < CHARINDEX(')', CLEANED_DRUGNAME) 
			THEN STUFF(CLEANED_DRUGNAME, CHARINDEX('(', CLEANED_DRUGNAME), (CHARINDEX(')', CLEANED_DRUGNAME) - CHARINDEX('(', CLEANED_DRUGNAME)) + 1, '')
		ELSE CLEANED_DRUGNAME
	END
WHERE NOTES IS NULL
    SET @COUNTER  = @COUNTER  + 1
END
GO

  
  
  
  --REMOVE BRACKETS
 DECLARE @COUNTER INT 
SET @COUNTER=1
WHILE ( @COUNTER <= 5)
BEGIN
 UPDATE DRUG_MAPPER  -- 4 TIMES
SET CLEANED_PROD_AI = CASE 
		WHEN CHARINDEX('(', CLEANED_PROD_AI) > 0 AND CHARINDEX(')', CLEANED_PROD_AI) > 0 AND CHARINDEX('(', CLEANED_PROD_AI) < CHARINDEX(')', CLEANED_PROD_AI) 
			THEN STUFF(CLEANED_PROD_AI, CHARINDEX('(', CLEANED_PROD_AI), (CHARINDEX(')', CLEANED_PROD_AI) - CHARINDEX('(', CLEANED_PROD_AI)) + 1, '')
		ELSE CLEANED_PROD_AI
	END
WHERE NOTES IS NULL
    SET @COUNTER  = @COUNTER  + 1
END
GO

-------------------------
--REMOVE WHITE SPACES 
 DECLARE @COUNTER INT 
SET @COUNTER=1
WHILE ( @COUNTER <= 5)
BEGIN

UPDATE DRUG_MAPPER
SET CLEANED_DRUGNAME =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_DRUGNAME, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
WHERE NOTES IS NULL

SET @COUNTER  = @COUNTER  + 1
END
GO 
------------------------------------
--REMOVE WHITE SPACES 
 DECLARE @COUNTER INT 
SET @COUNTER=1
WHILE ( @COUNTER <= 5)
BEGIN

UPDATE DRUG_MAPPER
SET CLEANED_PROD_AI =LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(CLEANED_PROD_AI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '')))
WHERE NOTES IS NULL

SET @COUNTER  = @COUNTER  + 1
END
GO 

