
--UPDATE DRUG_MAPPER WITH CLEANED DRUGNAMES AND PROD_AI
UPDATE  DRUG_MAPPER 
SET CLEANED_DRUGNAME = DRUG_MAPPER_TEMP.CLEANED_DRUGNAME

FROM DRUG_MAPPER_TEMP INNER JOIN DRUG_MAPPER ON 
DRUG_MAPPER_TEMP.DRUGNAME = DRUG_MAPPER.DRUGNAME
WHERE DRUG_MAPPER.NOTES IS NULL
----------------------------------
UPDATE  DRUG_MAPPER 
SET CLEANED_PROD_AI = DRUG_MAPPER_TEMP.CLEANED_PROD_AI

FROM DRUG_MAPPER_TEMP INNER JOIN DRUG_MAPPER ON 
DRUG_MAPPER_TEMP.PROD_AI = DRUG_MAPPER.PROD_AI 
WHERE DRUG_MAPPER.NOTES IS NULL
----------------------------------

--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.1
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CLEANED_DRUGNAME

		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
------------------------------------------------------------------
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.2
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CLEANED_PROD_AI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
--------------------------------------
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.3
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 

	IDD.DRUGNAME = CLEANED_DRUGNAME
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
-----------------------------------------------------------
		
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.4
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 
	IDD.DRUGNAME = CLEANED_PROD_AI
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 AND [RXNCONSO].SAB = 'RXNORM'
		AND [RXNCONSO].TTY IN ('MIN', 'IN', 'PIN')
-------------------------------------------------------

UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.5
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CLEANED_DRUGNAME

		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY ='IN'
-------------------------------------------------------------	
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.6
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CLEANED_PROD_AI
		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY = 'IN'
------------------------------------------------------------------

--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.7
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 
	IDD.DRUGNAME = CLEANED_DRUGNAME
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 
		AND [RXNCONSO].TTY = 'IN'
--------------------------------------------------------------------
		
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.8
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 
	IDD.DRUGNAME = CLEANED_PROD_AI
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		
		AND [RXNCONSO].TTY = 'IN'
---------------------------------------------------
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.9
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 

	RXNCONSO.STR = CLEANED_DRUGNAME

		 WHERE  NOTES IS NULL
		
--------------------------------------------------
		
		--MATCH WITH INSIDE ()	
UPDATE  DRUG_MAPPER 
SET RXAUI = [RXNCONSO].RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.10
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM [RXNCONSO] INNER JOIN DRUG_MAPPER ON 
	RXNCONSO.STR = CLEANED_PROD_AI
		 WHERE  NOTES IS NULL
	
------------------------------------------------------------------
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.11
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 
	IDD.DRUGNAME = CLEANED_DRUGNAME
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
		 
------------------------------------------------
		
--MATCH WITH INSIDE ()
UPDATE  DRUG_MAPPER 
SET RXAUI = RXNCONSO.RXAUI, RXCUI = [RXNCONSO].RXCUI,  NOTES = 9.12
, SAB = [RXNCONSO].SAB, TTY = [RXNCONSO].TTY, STR=[RXNCONSO].STR, CODE  =[RXNCONSO].CODE

FROM IDD INNER JOIN DRUG_MAPPER ON 
	IDD.DRUGNAME = CLEANED_PROD_AI
	INNER JOIN RXNCONSO ON RXNCONSO.RXAUI = IDD.RXAUI
		 WHERE  NOTES IS NULL
	
	
