
--<<<<<<<<<R E M A P P I  N G>>>>>>>>>>>>

UPDATE DRUG_MAPPER
SET    REMAPPING_RXCUI = RXCUI
	  ,REMAPPING_RXAUI = RXAUI
	  , REMAPPING_STR = STR
	  ,REMAPPING_SAB = SAB
	  ,REMAPPING_TTY = TTY
	  ,REMAPPING_CODE = CODE
	  ,REMAPPING_NOTES = '1'
WHERE SAB= 'RXNORM'
AND TTY = 'IN'
AND REMAPPING_NOTES IS NULL 
----------------------
DROP TABLE IF EXISTS  DRUG_MAPPER_2;
------------------------------------
SELECT  [DRUG_ID]
      ,[PRIMARYID]
      ,[DRUG_SEQ]
      ,[ROLE_COD]
	  ,[PERIOD]
      ,[DRUGNAME]
      ,[PROD_AI]
      ,[NOTES]
	  ,C.RXAUI AS RXAUI, C.RXCUI AS RXCUI , C.STR AS STR  , C.SAB AS SAB, C.TTY AS TTY, C.CODE AS CODE
       , CASE WHEN A.RXAUI IS NULL THEN [REMAPPING_NOTES] ELSE '2' END AS [REMAPPING_NOTES]
	   , B.RELA 
	   ,  CASE WHEN A.RXAUI IS NULL THEN REMAPPING_RXAUI ELSE A.RXAUI   END AS REMAPPING_RXAUI  
	   ,  CASE WHEN A.RXCUI IS NULL THEN REMAPPING_RXCUI ELSE A.RXCUI   END AS REMAPPING_RXCUI  
	   ,  CASE WHEN A.STR IS NULL THEN REMAPPING_STR ELSE A.STR   END AS REMAPPING_STR 
	   ,  CASE WHEN A.SAB IS NULL THEN REMAPPING_SAB ELSE A.SAB   END AS REMAPPING_SAB 
	   ,  CASE WHEN A.TTY IS NULL THEN REMAPPING_TTY ELSE A.TTY   END AS REMAPPING_TTY 
	   ,  CASE WHEN A.CODE IS NULL THEN REMAPPING_CODE ELSE A.CODE   END AS REMAPPING_CODE 
      INTO DRUG_MAPPER_2
FROM   RXNCONSO AS A INNER JOIN
             RXNREL AS B ON A.RXCUI = B.RXCUI1
			 AND (A.TTY = 'IN') AND A.SAB = 'RXNORM' 
			 RIGHT OUTER JOIN
             DRUG_MAPPER AS C ON B.RXCUI2 = C.RXCUI 
AND  REMAPPING_NOTES IS NULL
-----------------------------------
UPDATE DRUG_MAPPER_2  
SET        REMAPPING_NOTES = 'MAN_REM /', REMAPPING_RXAUI = HOPEFULLY_LAST_ONE_5_7_2021.LAST_RXAUI
		, REMAPPING_RXCUI = RXNCONSO.RXCUI, REMAPPING_STR = RXNCONSO.STR, REMAPPING_SAB = RXNCONSO.SAB
		, REMAPPING_TTY = RXNCONSO.TTY, REMAPPING_CODE = RXNCONSO.CODE
FROM     DRUG_MAPPER_2 INNER JOIN
               HOPEFULLY_LAST_ONE_5_7_2021 ON DRUG_MAPPER_2.STR = HOPEFULLY_LAST_ONE_5_7_2021.STR 
			   AND DRUG_MAPPER_2.RXAUI = HOPEFULLY_LAST_ONE_5_7_2021.RXAUI INNER JOIN
               RXNCONSO ON HOPEFULLY_LAST_ONE_5_7_2021.LAST_RXAUI = RXNCONSO.RXAUI
			   WHERE REMAPPING_NOTES IS NULL
			  
INSERT INTO DRUG_MAPPER_2
    (DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI
	, STR, SAB, TTY, CODE, REMAPPING_NOTES, RELA, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_SAB
	, REMAPPING_TTY, REMAPPING_CODE, 
    REMAPPING_STR)
SELECT  DRUG_MAPPER_2_1.DRUG_ID, DRUG_MAPPER_2_1.PRIMARYID, DRUG_MAPPER_2_1.DRUG_SEQ, DRUG_MAPPER_2_1.ROLE_COD
	, DRUG_MAPPER_2_1.PERIOD, DRUG_MAPPER_2_1.DRUGNAME, DRUG_MAPPER_2_1.PROD_AI, DRUG_MAPPER_2_1.NOTES, 
    DRUG_MAPPER_2_1.RXAUI, DRUG_MAPPER_2_1.RXCUI, DRUG_MAPPER_2_1.STR, DRUG_MAPPER_2_1.SAB, DRUG_MAPPER_2_1.TTY
	, DRUG_MAPPER_2_1.CODE, 'MAN2/'+ DRUG_MAPPER_2_1.REMAPPING_NOTES, DRUG_MAPPER_2_1.RELA, 
    A.LAST_RXAUI AS REMAPPING_RXAUI, RXNCONSO.RXCUI AS REMAPPING_RXCUI, RXNCONSO.SAB AS REMAPPING_SAB
	, RXNCONSO.TTY AS REMAPPING_TTY, RXNCONSO.CODE AS REMAPPING_CODE, RXNCONSO.STR AS REMAPPING_STR
      
FROM DRUG_MAPPER_2 AS DRUG_MAPPER_2_1 INNER JOIN HOPEFULLY_LAST_ONE_5_7_2021 A  ON A.RXAUI = DRUG_MAPPER_2_1.RXAUI
	AND A.STR = DRUG_MAPPER_2_1.STR INNER JOIN
    RXNCONSO ON A.LAST_RXAUI = RXNCONSO.RXAUI
	WHERE A.LAST_RXAUI IS NOT NULL
	AND LEFT(REMAPPING_NOTES,10) ='MAN_REM / ' 

DELETE FROM DRUG_MAPPER_2
WHERE LEFT(REMAPPING_NOTES,10) ='MAN_REM / ' 
-------------------------------------------------------
INSERT INTO DRUG_MAPPER_2 (
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME
, PROD_AI, NOTES, RXAUI, RXCUI, STR, SAB, TTY, CODE, RELA, REMAPPING_NOTES
, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_STR, REMAPPING_SAB
, REMAPPING_TTY, REMAPPING_CODE
)

SELECT [DRUG_ID]
      ,[PRIMARYID]
      ,[DRUG_SEQ]
      ,[ROLE_COD]
	  ,[PERIOD]
      ,[DRUGNAME]
      ,[PROD_AI]
      ,[NOTES]
	   ,E.RXAUI , E.RXCUI ,  E.STR  , E.SAB,  E.TTY, E.CODE, E.RELA 
       ,  '3' 
	   ,   A.RXAUI    AS REMAPPING_RXAUI  
	   ,   A.RXCUI    AS REMAPPING_RXCUI
	   ,   A.STR    AS REMAPPING_STR 
	   ,   A.SAB    AS REMAPPING_SAB 
	   ,   A.TTY    AS REMAPPING_TTY 
	   ,   A.CODE   AS REMAPPING_CODE 
	       			 
FROM   RXNCONSO AS A INNER JOIN
             RXNREL AS B ON A.RXCUI = B.RXCUI1  AND (A.TTY = 'IN') AND A.SAB = 'RXNORM'   INNER JOIN 
             RXNCONSO AS C ON B.RXCUI2 = C.RXCUI   INNER JOIN
             RXNREL AS D ON C.RXCUI = D.RXCUI1  AND D.RELA ='HAS_INGREDIENTS' AND C.SAB = 'VANDF'
			 AND C.TTY = 'IN' INNER JOIN
             DRUG_MAPPER_2 AS E ON D.RXCUI2 = E.RXCUI   AND REMAPPING_NOTES IS NULL

DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '3' )
AND REMAPPING_NOTES IS NULL
-----------------------------------------------------
	
UPDATE DRUG_MAPPER_2
SET    REMAPPING_RXCUI = RXNCONSO.RXCUI
		, REMAPPING_RXAUI = RXNCONSO.RXAUI
		, REMAPPING_STR = RXNCONSO.STR
		, REMAPPING_NOTES = '4'
		, REMAPPING_SAB = RXNCONSO.SAB
		, REMAPPING_TTY = RXNCONSO.TTY
		, REMAPPING_CODE = RXNCONSO.CODE
		
FROM  RXNCONSO INNER JOIN DRUG_MAPPER_2 ON RXNCONSO.RXCUI = DRUG_MAPPER_2.RXCUI

		 WHERE RXNCONSO.SAB = 'RXNORM'
		 AND RXNCONSO.TTY = 'IN'
		 AND REMAPPING_NOTES IS NULL
---------------------------------------------------------
UPDATE DRUG_MAPPER_2
SET    REMAPPING_RXCUI = RXNCONSO.RXCUI
		, REMAPPING_RXAUI = RXNCONSO.RXAUI
		, REMAPPING_STR = RXNCONSO.STR
		, REMAPPING_NOTES = '5'
		, REMAPPING_SAB = RXNCONSO.SAB
		, REMAPPING_TTY = RXNCONSO.TTY
		, REMAPPING_CODE = RXNCONSO.CODE
				
FROM  RXNCONSO RIGHT OUTER JOIN
         RXNREL ON RXNCONSO.RXAUI = RXNREL.RXAUI1 RIGHT OUTER JOIN
         DRUG_MAPPER_2 ON RXNREL.RXAUI2 = DRUG_MAPPER_2.RXAUI

		 WHERE RXNCONSO.SAB = 'RXNORM'
		 AND RXNCONSO.TTY = 'IN'
		AND  REMAPPING_NOTES IS NULL
	
------------------------------------------
INSERT INTO DBO.DRUG_MAPPER_2
(
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI, STR, SAB, TTY, CODE
, REMAPPING_NOTES, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_STR, REMAPPING_SAB, REMAPPING_TTY, REMAPPING_CODE
)
  		
   SELECT DISTINCT
    DRUG_MAPPER_2.DRUG_ID
   ,DRUG_MAPPER_2.PRIMARYID
   ,DRUG_MAPPER_2.DRUG_SEQ
   ,DRUG_MAPPER_2.ROLE_COD
   ,DRUG_MAPPER_2.PERIOD
   ,DRUG_MAPPER_2.DRUGNAME
   ,DRUG_MAPPER_2.PROD_AI
   ,DRUG_MAPPER_2.NOTES
   ,DRUG_MAPPER_2.RXAUI
   ,DRUG_MAPPER_2.RXCUI
   ,DRUG_MAPPER_2.STR
   ,DRUG_MAPPER_2.SAB
   ,DRUG_MAPPER_2.TTY
   ,DRUG_MAPPER_2.CODE
   ,'6' AS REMAPPING_NOTES
   ,RXNCONSO_1.RXAUI AS REMAPPING_RXAUI
   ,RXNCONSO_1.RXCUI AS REMAPPING_RXCUI
   ,RXNCONSO_1.STR AS REMAPPING_STR
   ,RXNCONSO_1.SAB AS REMAPPING_SAB
   ,RXNCONSO_1.TTY AS REMAPPING_TTY
   ,RXNCONSO_1.CODE AS REMAPPING_CODE

  FROM DBO.DRUG_MAPPER_2
  INNER JOIN DBO.RXNREL
    ON DRUG_MAPPER_2.RXCUI = RXNREL.RXCUI2
  INNER JOIN DBO.RXNCONSO
    ON RXNREL.RXCUI1 = RXNCONSO.RXCUI
  INNER JOIN DBO.RXNREL RXNREL_1
    ON RXNREL.RXCUI1 = RXNREL_1.RXCUI2
  INNER JOIN DBO.RXNCONSO RXNCONSO_1
    ON RXNREL_1.RXCUI1 = RXNCONSO_1.RXCUI
  WHERE RXNCONSO.SAB = 'MTHSPL'
  AND RXNCONSO_1.SAB = 'RXNORM'
  AND RXNCONSO_1.TTY = 'IN'
  AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL 
 

DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '6' )
AND REMAPPING_NOTES IS NULL
---------------------------------------------------------------------------------
INSERT INTO DBO.DRUG_MAPPER_2 
(
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI, STR, SAB
, TTY, CODE, REMAPPING_NOTES , REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_STR, REMAPPING_SAB
, REMAPPING_TTY, REMAPPING_CODE
)
    SELECT DISTINCT
    DRUG_MAPPER_2.DRUG_ID
   ,DRUG_MAPPER_2.PRIMARYID
   ,DRUG_MAPPER_2.DRUG_SEQ
   ,DRUG_MAPPER_2.ROLE_COD
   ,DRUG_MAPPER_2.PERIOD
   ,DRUG_MAPPER_2.DRUGNAME
   ,DRUG_MAPPER_2.PROD_AI
   ,DRUG_MAPPER_2.NOTES
   ,DRUG_MAPPER_2.RXAUI
   ,DRUG_MAPPER_2.RXCUI
   ,DRUG_MAPPER_2.STR
   ,DRUG_MAPPER_2.SAB
   ,DRUG_MAPPER_2.TTY
   ,DRUG_MAPPER_2.CODE
   ,'7' AS REMAPPING_NOTES  
   ,RXNCONSO_1.RXAUI AS REMAPPING_RXAUI
   ,RXNCONSO_1.RXCUI AS REMAPPING_RXCUI
   ,RXNCONSO_1.STR AS REMAPPING_STR
   ,RXNCONSO_1.SAB AS REMAPPING_SAB
   ,RXNCONSO_1.TTY AS REMAPPING_TTY
   ,RXNCONSO_1.CODE AS REMAPPING_CODE
  

FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNREL
  ON DRUG_MAPPER_2.RXCUI = RXNREL.RXCUI2
INNER JOIN DBO.RXNCONSO
  ON RXNREL.RXCUI1 = RXNCONSO.RXCUI
INNER JOIN DBO.RXNREL RXNREL_1
  ON RXNREL.RXCUI1 = RXNREL_1.RXCUI2
INNER JOIN DBO.RXNCONSO RXNCONSO_1
  ON RXNREL_1.RXCUI1 = RXNCONSO_1.RXCUI
WHERE DRUG_MAPPER_2.SAB = 'MMSL'
 AND RXNCONSO_1.SAB = 'RXNORM'
 AND RXNCONSO_1.TTY = 'IN'
AND REMAPPING_NOTES IS NULL
 AND RXNCONSO.SAB = 'RXNORM'
 AND RXNCONSO.TTY = 'SCDC'
 AND RXNCONSO_1.RXAUI !=11794211  
  AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL 

DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '7' )
AND REMAPPING_NOTES IS NULL


  ------------------------------------------------------
INSERT INTO DBO.DRUG_MAPPER_2 
(
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI
, RXCUI, STR, SAB, TTY, CODE, REMAPPING_NOTES, REMAPPING_RXAUI, REMAPPING_RXCUI
, REMAPPING_STR, REMAPPING_SAB, REMAPPING_TTY, REMAPPING_CODE
)
  	SELECT DISTINCT
    DRUG_MAPPER_2.DRUG_ID
   ,DRUG_MAPPER_2.PRIMARYID
   ,DRUG_MAPPER_2.DRUG_SEQ
   ,DRUG_MAPPER_2.ROLE_COD
   ,DRUG_MAPPER_2.PERIOD
   ,DRUG_MAPPER_2.DRUGNAME
   ,DRUG_MAPPER_2.PROD_AI
   ,DRUG_MAPPER_2.NOTES
   ,DRUG_MAPPER_2.RXAUI
   ,DRUG_MAPPER_2.RXCUI
   ,DRUG_MAPPER_2.STR
   ,DRUG_MAPPER_2.SAB
   ,DRUG_MAPPER_2.TTY
   ,DRUG_MAPPER_2.CODE
   ,'8' AS REMAPPING_NOTES
   ,RXNCONSO_1.RXAUI AS REMAPPING_RXAUI
   ,RXNCONSO_1.RXCUI AS REMAPPING_RXCUI
   ,RXNCONSO_1.STR AS REMAPPING_STR
   ,RXNCONSO_1.SAB AS REMAPPING_SAB
   ,RXNCONSO_1.TTY AS REMAPPING_TTY
   ,RXNCONSO_1.CODE AS REMAPPING_CODE


FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNREL
  ON DRUG_MAPPER_2.RXCUI = RXNREL.RXCUI2
INNER JOIN DBO.RXNCONSO
  ON RXNREL.RXCUI1 = RXNCONSO.RXCUI
INNER JOIN DBO.RXNREL RXNREL_1
  ON RXNREL.RXCUI1 = RXNREL_1.RXCUI2
INNER JOIN DBO.RXNCONSO RXNCONSO_1
  ON RXNREL_1.RXCUI1 = RXNCONSO_1.RXCUI
WHERE RXNCONSO.SAB = 'RXNORM'
 AND RXNCONSO.TTY = 'SCDC'
 AND RXNCONSO_1.SAB = 'RXNORM'
 AND RXNCONSO_1.TTY = 'IN'
  AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL

DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '8' )
AND REMAPPING_NOTES IS NULL

 ------------------------------
UPDATE DRUG_MAPPER_2
SET    REMAPPING_RXCUI = RXNCONSO.RXCUI   
		, REMAPPING_RXAUI = RXNCONSO.RXAUI
		, REMAPPING_STR = RXNCONSO.STR
		, REMAPPING_NOTES = '9'
		, REMAPPING_SAB = RXNCONSO.SAB
		, REMAPPING_TTY = RXNCONSO.TTY
		


FROM  RXNCONSO RIGHT OUTER JOIN
         RXNREL ON RXNCONSO.RXAUI = RXNREL.RXAUI1 RIGHT OUTER JOIN
         DRUG_MAPPER_2 ON RXNREL.RXAUI2 = DRUG_MAPPER_2.RXAUI

		 WHERE RXNCONSO.SAB = 'RXNORM'
		 AND RXNCONSO.TTY = 'IN'
		  AND REMAPPING_NOTES IS NULL
		  AND NOTES IS NOT NULL
----------------------------------------------------
INSERT INTO DBO.DRUG_MAPPER_2 
(
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI, STR
, SAB, TTY, CODE, REMAPPING_NOTES, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_STR
, REMAPPING_SAB, REMAPPING_TTY, REMAPPING_CODE
)
  		
  SELECT DISTINCT
    DRUG_MAPPER_2.DRUG_ID
   ,DRUG_MAPPER_2.PRIMARYID
   ,DRUG_MAPPER_2.DRUG_SEQ
   ,DRUG_MAPPER_2.ROLE_COD
   ,DRUG_MAPPER_2.PERIOD
   ,DRUG_MAPPER_2.DRUGNAME
   ,DRUG_MAPPER_2.PROD_AI
   ,DRUG_MAPPER_2.NOTES
   ,DRUG_MAPPER_2.RXAUI
   ,DRUG_MAPPER_2.RXCUI
   ,DRUG_MAPPER_2.STR
   ,DRUG_MAPPER_2.SAB
   ,DRUG_MAPPER_2.TTY
   ,DRUG_MAPPER_2.CODE
   ,'9' AS REMAPPING_NOTES
   ,RXNCONSO_1.RXAUI AS REMAPPING_RXAUI
   ,RXNCONSO_1.RXCUI AS REMAPPING_RXCUI
   ,RXNCONSO_1.STR AS REMAPPING_STR
   ,RXNCONSO_1.SAB AS REMAPPING_SAB
   ,RXNCONSO_1.TTY AS REMAPPING_TTY
   ,RXNCONSO_1.CODE AS REMAPPING_CODE

FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNREL
  ON DRUG_MAPPER_2.RXAUI = RXNREL.RXAUI2
INNER JOIN DBO.RXNCONSO
  ON RXNREL.RXAUI1 = RXNCONSO.RXAUI  
INNER JOIN DBO.RXNREL RXNREL_1
  ON RXNREL.RXAUI1 = RXNREL_1.RXAUI2
INNER JOIN DBO.RXNCONSO RXNCONSO_1
  ON RXNREL_1.RXAUI1 = RXNCONSO_1.RXAUI
WHERE RXNCONSO_1.SAB = 'RXNORM'
 AND RXNCONSO_1.TTY = 'IN'
 AND RXNCONSO.SAB = 'MTHSPL'
 AND RXNREL.RELA ='HAS_ACTIVE_MOIETY'
 
   AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL
 
DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '9' )
AND REMAPPING_NOTES IS NULL
----------------------------------------------------------
UPDATE DRUG_MAPPER_2
SET REMAPPING_NOTES = '10'
	, REMAPPING_RXAUI = RXNCONSO.RXAUI
   ,REMAPPING_RXCUI= RXNCONSO.RXCUI
   ,REMAPPING_STR= RXNCONSO.STR
   , REMAPPING_SAB= RXNCONSO.SAB
   , REMAPPING_TTY= RXNCONSO.TTY
   , REMAPPING_CODE= RXNCONSO.CODE
   
  
FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNCONSO
  ON DRUG_MAPPER_2.RXCUI = RXNCONSO.RXCUI

WHERE 
  RXNCONSO.TTY = 'IN'
  AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL
 ---------------------------------------------
INSERT INTO DBO.DRUG_MAPPER_2 
(
DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI, STR, SAB
, TTY, CODE, REMAPPING_NOTES, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_STR, REMAPPING_SAB
, REMAPPING_TTY, REMAPPING_CODE 
)
   SELECT DISTINCT
    DRUG_MAPPER_2.DRUG_ID
   ,DRUG_MAPPER_2.PRIMARYID
   ,DRUG_MAPPER_2.DRUG_SEQ
   ,DRUG_MAPPER_2.ROLE_COD
   ,DRUG_MAPPER_2.PERIOD
   ,DRUG_MAPPER_2.DRUGNAME
   ,DRUG_MAPPER_2.PROD_AI
   ,DRUG_MAPPER_2.NOTES
   ,DRUG_MAPPER_2.RXAUI
   ,DRUG_MAPPER_2.RXCUI
   ,DRUG_MAPPER_2.STR
   ,DRUG_MAPPER_2.SAB
   ,DRUG_MAPPER_2.TTY
   ,DRUG_MAPPER_2.CODE
   ,'11' AS REMAPPING_NOTES
   ,RXNCONSO_1.RXAUI AS REMAPPING_RXAUI
   ,RXNCONSO_1.RXCUI AS REMAPPING_RXCUI
   ,RXNCONSO_1.STR AS REMAPPING_STR
   ,RXNCONSO_1.SAB AS REMAPPING_SAB
   ,RXNCONSO_1.TTY AS REMAPPING_TTY
   ,RXNCONSO_1.CODE AS REMAPPING_CODE

FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNREL
  ON DRUG_MAPPER_2.RXAUI = RXNREL.RXAUI2
INNER JOIN DBO.RXNCONSO
  ON RXNREL.RXAUI1 = RXNCONSO.RXAUI
INNER JOIN DBO.RXNREL RXNREL_1
  ON RXNREL.RXAUI1 = RXNREL_1.RXAUI2
INNER JOIN DBO.RXNCONSO RXNCONSO_1
  ON RXNREL_1.RXAUI1 = RXNCONSO_1.RXAUI
WHERE RXNCONSO_1.SAB = 'MMSL'
 AND RXNCONSO_1.TTY = 'IN'
 AND DRUG_MAPPER_2.SAB = 'MMSL'
   AND DRUG_MAPPER_2.REMAPPING_NOTES IS NULL
    AND RXNCONSO_1.RXAUI NOT IN (2604414, 1182299,1173735,1287235)

DELETE FROM DRUG_MAPPER_2
WHERE  DRUG_ID IN  (SELECT DRUG_ID FROM DRUG_MAPPER_2 WHERE REMAPPING_NOTES = '11' )
AND REMAPPING_NOTES IS NULL
------------------------------------------------------
UPDATE DRUG_MAPPER_2 
SET  REMAPPING_NOTES = '12'     
 ,REMAPPING_RXAUI = RXNCONSO.RXAUI
 ,REMAPPING_RXCUI = RXNCONSO.RXCUI
 ,REMAPPING_STR = RXNCONSO.STR
 ,REMAPPING_SAB = RXNCONSO.SAB
 ,REMAPPING_TTY = RXNCONSO.TTY
 ,REMAPPING_CODE = RXNCONSO.CODE
FROM DBO.DRUG_MAPPER_2
INNER JOIN DBO.RXNCONSO
 ON RXNCONSO.STR =  CASE 
		WHEN CHARINDEX('(', REMAPPING_STR) > 0 AND CHARINDEX(')', REMAPPING_STR) > 0 AND CHARINDEX('(', REMAPPING_STR) < CHARINDEX(')', REMAPPING_STR) 
			THEN STUFF(REMAPPING_STR, CHARINDEX('(', REMAPPING_STR), (CHARINDEX(')', REMAPPING_STR) - CHARINDEX('(', REMAPPING_STR)) + 1, '')
		ELSE REMAPPING_STR
	END
WHERE RXNCONSO.SAB = 'RXNORM'
AND RXNCONSO.TTY IN ( 'IN', 'MIN', 'PIN')
AND REMAPPING_NOTES IN ('9','10','11')
----------------------------------------------------
UPDATE  DRUG_MAPPER_2
SET     REMAPPING_NOTES = 'TO BE DELETED'

FROM      DRUG_MAPPER_2 INNER JOIN
                   RXNREL ON DRUG_MAPPER_2.REMAPPING_RXCUI = RXNREL.RXCUI2 INNER JOIN
                   RXNCONSO ON RXNREL.RXCUI1 = RXNCONSO.RXCUI
				   WHERE RXNCONSO.SAB='RXNORM'
				   AND RXNCONSO.TTY='IN'
				   AND    REMAPPING_NOTES = '12'
--------------------------------------------------
INSERT INTO DRUG_MAPPER_2
                   (DRUG_ID, PRIMARYID, DRUG_SEQ, ROLE_COD, PERIOD, DRUGNAME, PROD_AI, NOTES, RXAUI, RXCUI, STR, SAB
				   , TTY, CODE, RELA, REMAPPING_NOTES, REMAPPING_RXCUI, REMAPPING_SAB, REMAPPING_TTY, REMAPPING_CODE
				   , REMAPPING_STR, 
                   REMAPPING_RXAUI)
SELECT  DRUG_MAPPER_2_1.DRUG_ID, DRUG_MAPPER_2_1.PRIMARYID, DRUG_MAPPER_2_1.DRUG_SEQ, DRUG_MAPPER_2_1.ROLE_COD
				   , DRUG_MAPPER_2_1.PERIOD, DRUG_MAPPER_2_1.DRUGNAME, DRUG_MAPPER_2_1.PROD_AI, DRUG_MAPPER_2_1.NOTES, 
                   DRUG_MAPPER_2_1.RXAUI, DRUG_MAPPER_2_1.RXCUI, DRUG_MAPPER_2_1.STR, DRUG_MAPPER_2_1.SAB, DRUG_MAPPER_2_1.TTY
				   , DRUG_MAPPER_2_1.CODE, DRUG_MAPPER_2_1.RELA, '13' AS EXPR7, RXNCONSO.RXCUI AS EXPR1, 
                   RXNCONSO.SAB AS EXPR2, RXNCONSO.TTY AS EXPR3, RXNCONSO.CODE AS EXPR4, RXNCONSO.STR AS EXPR5, RXNCONSO.RXAUI AS EXPR6
FROM      DRUG_MAPPER_2 AS DRUG_MAPPER_2_1 INNER JOIN
                   RXNREL ON DRUG_MAPPER_2_1.REMAPPING_RXCUI = RXNREL.RXCUI2 INNER JOIN
                   RXNCONSO ON RXNREL.RXCUI1 = RXNCONSO.RXCUI
				   WHERE REMAPPING_NOTES ='TO BE DELETED'
				   AND  RXNCONSO.SAB='RXNORM'
				   AND RXNCONSO.TTY='IN'

DELETE FROM DRUG_MAPPER_2
WHERE   (REMAPPING_NOTES = 'TO BE DELETED')

 
--DELETE DUPLICATED ROWS
---------------------------
WITH CTE AS(
   SELECT  [DRUG_ID] ,[RXAUI] ,[REMAPPING_RXAUI],
      
        ROW_NUMBER() OVER(PARTITION BY   [DRUG_ID] ,[RXAUI] ,[REMAPPING_RXAUI]
		ORDER BY   [DRUG_ID] ,[RXAUI] ,[REMAPPING_RXAUI]
		)ROW_NUMBER
   FROM DRUG_MAPPER_2
)
DELETE FROM CTE WHERE ROW_NUMBER > 1;

-------------------------------------



UPDATE DRUG_MAPPER_2
SET REMAPPING_RXCUI = RXNCONSO.RXCUI,
    REMAPPING_STR = RXNCONSO.STR,
    REMAPPING_SAB = RXNCONSO.SAB,
    REMAPPING_TTY = RXNCONSO.TTY,
    REMAPPING_CODE = RXNCONSO.CODE
FROM DRUG_MAPPER_2
INNER JOIN RXNCONSO
  ON DRUG_MAPPER_2.REMAPPING_RXAUI = RXNCONSO.RXAUI
WHERE REMAPPING_RXAUI IS NOT NULL
------------------------
UPDATE DRUG_MAPPER_2
SET REMAPPING_RXAUI = RXNCONSO.RXAUI,
    REMAPPING_RXCUI = RXNCONSO.RXCUI,
    REMAPPING_STR = RXNCONSO.STR,
    REMAPPING_SAB = RXNCONSO.SAB,
    REMAPPING_TTY = RXNCONSO.TTY,
    REMAPPING_CODE = RXNCONSO.CODE,
    REMAPPING_NOTES = '14'
FROM DRUG_MAPPER_2
INNER JOIN RXNCONSO
  ON DRUG_MAPPER_2.REMAPPING_RXCUI = RXNCONSO.RXCUI
WHERE (RXNCONSO.SAB = 'RXNORM')
AND (RXNCONSO.TTY = 'IN')
AND DRUG_MAPPER_2.SAB != 'RXNORM'
------------------------
UPDATE DRUG_MAPPER_2
SET REMAPPING_RXAUI = RXNCONSO.RXAUI,
    REMAPPING_RXCUI = RXNCONSO.RXCUI,
    REMAPPING_STR = RXNCONSO.STR,
    REMAPPING_SAB = RXNCONSO.SAB,
    REMAPPING_TTY = RXNCONSO.TTY,
    REMAPPING_CODE = RXNCONSO.CODE,
    REMAPPING_NOTES = '15'
FROM DRUG_MAPPER_2
INNER JOIN RXNCONSO
  ON DRUG_MAPPER_2.REMAPPING_RXCUI = RXNCONSO.RXCUI
WHERE (RXNCONSO.SAB = 'RXNORM')
AND (RXNCONSO.TTY = 'IN')
AND (DRUG_MAPPER_2.SAB = 'RXNORM')
AND (DRUG_MAPPER_2.TTY NOT IN ('IN', 'MIN'))
----------------------------------------------------

--CREATE REMAPPING TABLE
DROP TABLE FAERS_B.dbo.MANUAL_REMAPPER;
CREATE TABLE FAERS_B.dbo.MANUAL_REMAPPER (
 COUNT INT
 ,SOURCE_DRUGNAME VARCHAR(3000) NULL
 ,SOURCE_RXAUI VARCHAR(8) NULL
 ,SOURCE_RXCUI VARCHAR(8) NULL
 , SOURCE_SAB VARCHAR(20)
 , SOURCE_TTY VARCHAR(20)
 ,FINAL_RXAUI BIGINT NULL
 ,NOTES VARCHAR(100) NULL
)
;

------------------------------------------------------------
INSERT INTO MANUAL_REMAPPER
                 ( COUNT, SOURCE_DRUGNAME, SOURCE_RXAUI,SOURCE_RXCUI, SOURCE_SAB, SOURCE_TTY)
SELECT COUNT(DRUGNAME) AS COUNT,DRUGNAME, REMAPPING_RXAUI, REMAPPING_RXCUI , REMAPPING_SAB, REMAPPING_TTY 
FROM    DRUG_MAPPER_2
WHERE REMAPPING_NOTES IS NOT NULL
GROUP BY DRUGNAME, REMAPPING_RXAUI, REMAPPING_RXCUI, REMAPPING_SAB, REMAPPING_TTY;



--  MANUAL REMAPPING USING MS ACCESS, THEN LAOD IT BACK TO SQL SERVER,FAERS_B
-----------------------------------------------------

SELECT
  DRUG_MAPPER_2.DRUG_ID,
  DRUG_MAPPER_2.PRIMARYID,
  DRUG_MAPPER_2.DRUG_SEQ,
  DRUG_MAPPER_2.ROLE_COD,
  DRUG_MAPPER_2.PERIOD,
  DRUG_MAPPER_2.DRUGNAME,
  DRUG_MAPPER_2.PROD_AI,
  DRUG_MAPPER_2.NOTES,
  DRUG_MAPPER_2.RXAUI,
  DRUG_MAPPER_2.RXCUI,
  DRUG_MAPPER_2.STR,
  DRUG_MAPPER_2.SAB,
  DRUG_MAPPER_2.TTY,
  DRUG_MAPPER_2.CODE,
  MANUAL_REMAPPER.FINAL_RXAUI,
  RXNCONSO.RXCUI AS REMAPPING_RXCUI,
  RXNCONSO.STR AS REMAPPING_STR,
  RXNCONSO.SAB AS REMAPPING_SAB,
  RXNCONSO.TTY AS REMAPPING_TTY,
  RXNCONSO.CODE AS REMAPPING_CODE INTO DRUG_MAPPER_3
FROM MANUAL_REMAPPER
INNER JOIN RXNCONSO
  ON MANUAL_REMAPPER.FINAL_RXAUI = RXNCONSO.RXAUI
RIGHT OUTER JOIN DRUG_MAPPER_2
  ON MANUAL_REMAPPER.SOURCE_RXCUI = DRUG_MAPPER_2.REMAPPING_RXCUI;
----------------------------------------------------------------------------------------------

WITH CTE AS(
   SELECT  *,
      
        ROW_NUMBER() OVER(PARTITION BY   [DRUG_ID] ,DRUG_SEQ ,FINAL_RXAUI
		ORDER BY   PERIOD
		)ROW_NUMBER
   FROM DRUG_MAPPER_3
)
DELETE FROM CTE WHERE ROW_NUMBER > 1;